### PR TITLE
NXBT-1779: Use target platform filter in remote package listing

### PR DESCRIPTION
**Pull request by yjulienne-nuxeo**

### CODE REVIEW

**Review by jcarsique — COMMENTED** [review]
It sounds good to filter with the current target platform by default but how is it disabled?
There are API breaking changes. Why not creating new method signatures and keep compliance? 
There are missing and out-of-date `@since` annotations.

**Comment by yjulienne-nuxeo** [comment]
I don't see the point of disabling it but maybe you have use cases, we can discuss it.
👍 about the API breaking changes, I'll keep the old methods as deprecated because I think it's really better to use the new ones and benefit the TP filter.
I'll take a look at the `@since` annotations

**Comment by jcarsique** [comment]
@yjulienne-nuxeo :+1: as you suggest about the first point, implementing `--relax` with the `mp-listall` command is a very good option to match all requirements.

**Comment by yjulienne-nuxeo** [comment]
@jcarsique I pretty much refactored everything since your review because I noticed some missing changes while adding the `--relax` option.
So it might be a good idea to review it all ;)

**Review by jcarsique — APPROVED** [review]

**Comment by jcarsique** [comment]
:+1:

**Pull request merged**
